# Generated by Django 2.2.6 on 2020-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_courtsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsession',
            name='purpose',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
