# Generated by Django 2.2.6 on 2020-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200426_1309'),
        ('cases', '0039_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='client',
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ManyToManyField(to='clients.Client'),
        ),
    ]
