# Generated by Django 2.2.6 on 2020-06-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casearchive',
            options={'verbose_name': 'Case Archives', 'verbose_name_plural': 'Case Archives'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'verbose_name': 'Frequency', 'verbose_name_plural': 'Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='legalargument',
            options={'verbose_name': 'Legal Argument', 'verbose_name_plural': 'Legal Arguments'},
        ),
        migrations.AlterModelOptions(
            name='prioritylevel',
            options={'verbose_name': 'Priority Level', 'verbose_name_plural': 'Priority Levels'},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'verbose_name': 'Representation', 'verbose_name_plural': 'Representations'},
        ),
        migrations.AddField(
            model_name='casetask',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Frequency'),
        ),
    ]
