# Generated by Django 2.2.6 on 2020-07-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0014_auto_20200703_0956'),
        ('cases', '0045_auto_20200623_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='lead_professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_professional', to='lawyers.Lawyer'),
        ),
        migrations.AddField(
            model_name='case',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.Team'),
        ),
    ]
