# Generated by Django 2.2.6 on 2020-07-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_auto_20200706_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='CaseType',
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.CaseType'),
        ),
    ]
