# Generated by Django 2.2.6 on 2020-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_auto_20200706_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='pro_bono',
        ),
    ]
