# Generated by Django 2.2.6 on 2020-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0048_remove_case_pro_bono'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
