# Generated by Django 2.2.6 on 2020-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0049_process_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_file',
            field=models.FileField(null=True, upload_to='processes/'),
        ),
        migrations.AlterField(
            model_name='case',
            name='suit_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
