# Generated by Django 2.2.6 on 2020-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0051_process_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='aisle_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='process',
            name='box_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='process',
            name='shelf',
            field=models.CharField(default='', max_length=250),
        ),
    ]
