# Generated by Django 2.2.6 on 2020-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0052_auto_20200710_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
