# Generated by Django 2.2.6 on 2020-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0054_auto_20200713_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='aisle_number',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='box_number',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='shelf',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
