# Generated by Django 2.2.6 on 2020-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0055_auto_20200713_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
