# Generated by Django 2.2.6 on 2020-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0056_case_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casearchive',
            options={'verbose_name': 'Archived  Cases', 'verbose_name_plural': 'Archived Cases'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='aisle_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='casearchive',
            name='archive_location',
        ),
        migrations.AddField(
            model_name='casearchive',
            name='date_archived',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='aisle_number',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='box_number',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='shelf',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
