# Generated by Django 2.2.6 on 2020-07-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0057_auto_20200714_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
