# Generated by Django 2.2.6 on 2020-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0058_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='casearchive',
            name='aisle_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='casearchive',
            name='box_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='casearchive',
            name='shelf',
            field=models.CharField(default='', max_length=250),
        ),
    ]
