# Generated by Django 2.2.6 on 2020-07-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0059_auto_20200714_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bod', models.TextField()),
                ('next_business', models.DateTimeField()),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case')),
            ],
        ),
    ]
