# Generated by Django 2.2.6 on 2020-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0060_postaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postaction',
            options={'verbose_name': 'Post Action Report', 'verbose_name_plural': 'Post Action Report'},
        ),
        migrations.AddField(
            model_name='postaction',
            name='title',
            field=models.CharField(default='Ipsum Lorem', max_length=250),
        ),
    ]
