# Generated by Django 2.2 on 2020-08-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0061_auto_20200722_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
