# Generated by Django 2.2 on 2020-08-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0062_representative_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=250, null=True)),
                ('case_number', models.CharField(max_length=250, null=True)),
                ('suit_number', models.CharField(max_length=250, null=True)),
                ('client_name', models.CharField(max_length=250, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request From Archive',
                'verbose_name_plural': 'Request From Archives',
            },
        ),
    ]
