# Generated by Django 2.2 on 2020-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0066_auto_20200925_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaction',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
