# Generated by Django 2.2 on 2020-10-21 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20201002_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0068_auto_20201002_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='cases.Case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='EngagementTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='terms/')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'verbose_name': 'Terms of Engagement',
                'verbose_name_plural': 'Terms of Engagement',
            },
        ),
    ]
