# Generated by Django 2.2 on 2021-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0072_auto_20201023_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentenquiry',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Payment Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name_plural': 'Payment Status'},
        ),
    ]
