# Generated by Django 2.2 on 2021-10-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0023_user_team'),
        ('cases', '0073_auto_20210325_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='staff',
            field=models.ManyToManyField(to='lawyers.OtherStaff'),
        ),
    ]
