# Generated by Django 2.2 on 2021-10-27 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0075_auto_20211026_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementterm',
            name='terms',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
