# Generated by Django 2.2 on 2021-10-27 22:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0076_auto_20211027_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
