# Generated by Django 2.2 on 2021-10-29 15:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0078_auto_20211027_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='chinese_wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ManyToManyField(blank=True, null=True, to='lawyers.Lawyer'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
