# Generated by Django 2.2 on 2021-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0024_auto_20211027_2117'),
        ('cases', '0079_auto_20211029_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ManyToManyField(blank=True, null=True, to='lawyers.Lawyer')),
                ('staff', models.ManyToManyField(blank=True, null=True, to='lawyers.OtherStaff')),
            ],
        ),
    ]
