# Generated by Django 2.2 on 2021-10-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0081_chinesewall_mycase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chinesewall',
            old_name='lawyer',
            new_name='chinese_lawyer',
        ),
        migrations.RenameField(
            model_name='chinesewall',
            old_name='staff',
            new_name='chineses_staff',
        ),
    ]
