# Generated by Django 2.2 on 2021-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0082_auto_20211031_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Succesfull', 'SUCCESSFULL'), ('APPROVED', 'APPROVED'), ('Accepted', 'ACCEPTED'), ('Pending', 'PENDING')], default='male', max_length=100),
        ),
    ]
