# Generated by Django 2.2 on 2021-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0083_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Succesfull', 'SUCCESSFULL'), ('APPROVED', 'APPROVED'), ('Accepted', 'ACCEPTED'), ('Pending', 'PENDING')], default='Pending', max_length=100),
        ),
    ]
