# Generated by Django 2.2 on 2021-11-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0084_auto_20211111_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
