# Generated by Django 2.2 on 2021-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0085_auto_20211115_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
