# Generated by Django 2.2 on 2022-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0087_auto_20220119_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='time_spent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
