# Generated by Django 2.2 on 2022-01-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0089_auto_20220119_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='hour_payment',
            new_name='hour_time',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='minutes_payment',
            new_name='minutes_time',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='seconds_payment',
            new_name='seconds_time',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='charge_payment',
            new_name='total_charge_payment',
        ),
    ]
