# Generated by Django 2.2 on 2022-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0091_expense_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Succesfull', 'SUCCESSFULL'), ('APPROVED', 'APPROVED'), ('Accepted', 'ACCEPTED'), ('Pending', 'PENDING')], default='Pending', max_length=100),
        ),
    ]
