# Generated by Django 2.2 on 2022-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0092_auto_20220125_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Succesfull', 'SUCCESSFULL'), ('APPROVED', 'APPROVED'), ('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('', '')], default='', max_length=100),
        ),
    ]
