# Generated by Django 2.2 on 2022-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0093_auto_20220125_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Succesfull', 'SUCCESSFULL'), ('APPROVED', 'APPROVED'), ('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('Already_exit', 'Already_exit')], default='Already_exit', max_length=100),
        ),
    ]
