# Generated by Django 2.2 on 2022-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0094_auto_20220125_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Denied', 'Denied'), ('Approved', 'Approved'), ('Expense_Pending', 'Expense_Pending'), ('Already_exit', 'Already_exit')], default='Already_exit', max_length=100),
        ),
    ]
