# Generated by Django 2.2 on 2022-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0096_auto_20220125_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.CharField(choices=[('Denied', 'Denied'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Exists', 'Exists')], default='Exists', max_length=100),
        ),
    ]
