# Generated by Django 2.2 on 2022-02-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0097_expense_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charge_payment', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Total_amount', models.FloatField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cases', to='cases.Case')),
                ('name_task', models.ManyToManyField(to='cases.Timer')),
            ],
        ),
    ]
