# Generated by Django 2.2 on 2022-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0100_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_expense',
            field=models.FloatField(null=True),
        ),
    ]
