# Generated by Django 2.2 on 2022-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0101_invoice_total_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
