# Generated by Django 2.2 on 2022-03-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0102_timer_date_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='date_created',
        ),
    ]
