# Generated by Django 2.2 on 2022-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0104_termsofengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofengagement',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
