# Generated by Django 2.2 on 2022-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0105_termsofengagement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='cases.Category'),
        ),
    ]
