# Generated by Django 2.2 on 2022-08-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0106_auto_20220419_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-date_added'], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
    ]
