# Generated by Django 2.2 on 2022-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0107_auto_20220826_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetask',
            options={'ordering': ['-deadline'], 'verbose_name': 'Case Task', 'verbose_name_plural': 'Case Tasks'},
        ),
        migrations.AddField(
            model_name='casetask',
            name='dated_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
