# Generated by Django 2.2 on 2022-08-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0108_auto_20220826_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetask',
            options={'ordering': ['dated_created', 'deadline'], 'verbose_name': 'Case Task', 'verbose_name_plural': 'Case Tasks'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['date_added'], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
    ]
