# Generated by Django 2.2 on 2022-10-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0109_auto_20220826_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ManyToManyField(blank=True, to='cases.Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ManyToManyField(blank=True, to='lawyers.Lawyer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='staff',
            field=models.ManyToManyField(blank=True, to='lawyers.OtherStaff'),
        ),
    ]
