# Generated by Django 2.2 on 2022-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0110_auto_20221028_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesewall',
            name='chinese_lawyer',
            field=models.ManyToManyField(blank=True, to='lawyers.Lawyer'),
        ),
        migrations.AlterField(
            model_name='chinesewall',
            name='chineses_staff',
            field=models.ManyToManyField(blank=True, to='lawyers.OtherStaff'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='expenses',
            field=models.ManyToManyField(blank=True, to='cases.Expense'),
        ),
    ]
