# Generated by Django 2.2 on 2022-10-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0111_auto_20221028_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-date_added'], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
    ]
