# Generated by Django 2.2 on 2023-09-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0112_auto_20221028_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Representative'),
        ),
    ]
