# Generated by Django 2.2.6 on 2020-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_docfile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='date_returned',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
