# Generated by Django 2.2.6 on 2020-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20200513_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
