# Generated by Django 2.2.6 on 2020-05-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20200513_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='available',
        ),
    ]
