# Generated by Django 2.2.6 on 2020-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_remove_document_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
