# Generated by Django 2.2.6 on 2020-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_auto_20200422_2333'),
        ('wills', '0013_auto_20200514_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='user',
        ),
        migrations.AddField(
            model_name='agreement',
            name='user',
            field=models.ManyToManyField(to='lawyers.Lawyer'),
        ),
    ]
