# Generated by Django 2.2.6 on 2020-06-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wills', '0014_auto_20200612_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='user',
        ),
        migrations.AddField(
            model_name='agreement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
