# Generated by Django 2.2.6 on 2020-07-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_auto_20200422_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField()),
                ('description', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avi/')),
                ('lawyer', models.ManyToManyField(to='lawyers.Lawyer')),
                ('support_staff', models.ManyToManyField(to='lawyers.OtherStaff')),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='lawyers.Lawyer')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
