# Generated by Django 2.2.6 on 2020-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0013_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
