# Generated by Django 2.2.6 on 2020-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0014_auto_20200703_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Office Manager'), (2, 'Front Desk'), (3, 'Secretary'), (4, 'Archives')], primary_key=True, serialize=False),
        ),
    ]
