# Generated by Django 2.2 on 2020-08-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_auto_20200805_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherstaff',
            options={'verbose_name': 'Support Staff', 'verbose_name_plural': 'Support Staff'},
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherstaff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
