# Generated by Django 2.2 on 2020-08-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0018_auto_20200807_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerstatus',
            name='title',
            field=models.CharField(default='ROLE', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.LawyerStatus'),
        ),
        migrations.AlterField(
            model_name='lawyerstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
