# Generated by Django 2.2 on 2020-10-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0021_team_practice_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'ordering': ['user'], 'verbose_name': 'Lawyer', 'verbose_name_plural': 'Lawyers'},
        ),
        migrations.AlterModelOptions(
            name='otherstaff',
            options={'ordering': ['user'], 'verbose_name': 'Support Staff', 'verbose_name_plural': 'Support Staff'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
