# Generated by Django 2.2 on 2021-10-27 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0023_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
