# Generated by Django 2.2 on 2021-11-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0024_auto_20211027_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='per_hour_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='per_hour_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
