# Generated by Django 2.2 on 2021-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0025_auto_20211110_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='per_hour_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
