# Generated by Django 2.2 on 2022-03-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondents', '0002_auto_20200501_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
