# Generated by Django 2.2.6 on 2020-05-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_auto_20200422_2333'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='requested',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('date_returned', models.DateField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.OtherStaff')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Book')),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.Lawyer')),
            ],
        ),
    ]
