# Generated by Django 2.2.6 on 2020-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200511_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
