# Generated by Django 2.2.6 on 2020-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200511_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
