# Generated by Django 2.2.6 on 2020-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200512_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
