# Generated by Django 2.2.6 on 2020-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_bookhistory_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='date_approved',
            field=models.DateField(null=True),
        ),
    ]
